### ISSUE TITLE
Contenido del sitio

### ISSUE THREAD

**Issue by luifer991** [luifer991/paladin#4]
Por favor buscar recursos para mejorar el contenido del sitio y adaptarlo a las necesidades de la pagina que estamos construyendo, ademas buscar propuestas para el contenido del sitio y mejorarlo se recomienda buscar

1. Imagenes llamativas
2. Contenido ya sea copiado de otras webs que sean similares pero en otro idioma
3. pueden usar IA generativa o tambien imagenes extraidas de otras web
4. dejar el diseño como está ya que es una plantilla y debemos mantener el estilo
5. cambiar el color del background a un color mas parecido al de PaladinDotBuild
6. Buscar una paleta de colores adecuada

Sé bien que esta issue tiene demasiadas tareas, cada quien puede dejar el comentario de que tarea es la que va a realizar
son libres de hacer la parte que mas deseen solo avisen que parte van a trabajar cada uno puede autoasignarse la tarea que mas les convenga mucha suerte y vamos con toda muchachos

**Comment by pgonzalesmv** [comment]
En cuanto a la fuente puede ser poppins con sus jerarquías por tamaños, como la de esta web https://www.plain.pe
![image](https://github.com/user-attachments/assets/ec63bafe-1fce-4b63-a2a6-fa9480cb0a97)

La paleta puede ser la siguiente, color negro para fondo y contraste de sombras, texto blanco, azules para botones y cyan para resaltar texto
![image](https://github.com/user-attachments/assets/4a64c372-4484-42ef-bf7a-c9e3cc180e6d)

**Comment by luifer991** [comment]
en cuanto a la fuente a mi parecer es algo generica aunque funcionaria, porque es bastante conocida y muy utilizada. en cuanto a la paleta de colores con 3 es suficiente ya que muchos colores le quitan consistencia, el del el fondo me gusta el  #1f1f1f
para botones me gustaria el color #2700ff y el texto blanco estaria bien.

me gustaria saber que opinan los demas si hay mas ideas o si lo dejamos con esos tres colores

https://private-user-images.githubusercontent.com/55267386/370857188-4a64c372-4484-42ef-bf7a-c9e3cc180e6d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcyOTkxNTYsIm5iZiI6MTcyNzI5ODg1NiwicGF0aCI6Ii81NTI2NzM4Ni8zNzA4NTcxODgtNGE2NGMzNzItNDQ4NC00MmVmLWJmN2EtYzllM2NjMTgwZTZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI1VDIxMTQxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM3ZWVmM2I4YzM5YWNmYzUwOTljNzdmMWVhMjkyYTg1MDZiYTRkZGIwNDJlZDNkYmFiZDRiYWQ3MmY0MTgwODEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.C9Zyt_6sgYyanBxYuacmNmMwBrO1XGBYvoAUFdlBOTM

#1f1f1f  fondo #2700ff botones #ffffff texto

podriamos incluir el cyan como para el borde de los botones. y si algo algunos brillos que se añadan para que sea mas llamativo como hacen muchas webs modernas
